apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsl-deployment
  labels:
    app.kubernetes.io/name: fsl
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: fsl
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fsl
    spec:
      containers:
      - name: fls
        image: 629261288378.dkr.ecr.us-east-2.amazonaws.com/fsl:latest
        ports:
        - containerPort: 8080